# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
  name: Hem
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  unit_system: metric
  time_zone: Europe/Stockholm

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  server_port: !secret server_port
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
