#Home assistant config
homeassistant:
  name: Hem
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  unit_system: metric
  time_zone: Europe/Stockholm

  packages: !include_dir_merge_named packages

# Default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  server_port: !secret server_port
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: !secret base_url

# Enablers
discovery:
ios:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml

#Log bans
logger:
  default: critical
  logs:
    homeassistant.components.http.ban: warning
