#Home assistant config
homeassistant:
  name: Hem
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  unit_system: metric
  time_zone: Europe/Stockholm
  
  packages: !include_dir_merge_named packages

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  server_port: !secret server_port
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: !secret base_url
  
# Enablers
discovery:
ios:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

logger:
  default: critical
  logs:
    homeassistant.components.http.ban: warning