homeassistant:
  name: Hem
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml
  currency: SEK
default_config:

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
group: !include groups.yaml
scene: !include scenes.yaml
light: !include light.yaml

## Värmepumpar
climate: !include_dir_merge_list includes/climate/

## Media players
media_player: !include_dir_merge_list includes/media_player/

## REST 
rest: !include_dir_merge_list includes/rest/

## Templates
template: !include_dir_merge_list includes/templates/

## Sensors
sensor: !include_dir_merge_list includes/sensors/

## Dashboards
lovelace:
  mode: storage
  dashboards:
    lovelace-floorplan:
      mode: yaml
      title: Floorplan
      icon: 'mdi:floor-plan'
      show_in_sidebar: true
      filename: floorplan.yaml

http:  
  server_port: !secret server_port
  
smartir:
  check_updates: false

browser_mod:
  devices:
    375553f6-33529b78:
      name: lenovotablet
      force_stay_awake: true
  disable:
    - all

# Enablers
ios:
cloud:
nordpool:

# Google Calendar
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

# Text to speech
tts:
  - platform: google_translate
 
recorder:
  exclude:
    domains:
      - updater
      - media_player
      - group
      - binary_sensor
      - automation

logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.date
      - sensor.current_date
      - sensor.current_time