title: Floorplan
decluttering_templates: !include_dir_named floorplan/
views:
  - title: Floorplan
    path: floorplan
    visible:
      - user: 7fdffcaeaaf54b98b330878819fde53b
    panel: true
    icon: 'mdi:floor-plan'
    badges: []
    cards:
      - type: 'custom:config-template-card'
        entities:
          - light.hallbyra
          - light.hall_sovrum_1
          - light.hall_ytterdorr_1
          - light.trappa
          - light.vardagsrumsbord
          - light.fonsterlampa_mot_uterum
          - light.fonsterlampa_vardagsrum
          - switch.danslampa
          - light.kokslampa
          - light.diskbank
          - light.taklampa_signes_rum
          - sensor.sunlight_opacity
        variables:
          floorplan:
            leftCrop: 63
            topCrop: 36
            bottomCrop: 10
            width: 1793
            height: 955
          setOpacity: |
            entity => {
              if(states[entity].state === 'on') {
                if (typeof states[entity].attributes.brightness !== 'undefined') {
                  return states[entity].attributes.brightness / 255;
                }
                return 1;
              }
              return 0;
            }
          setPosition: |
            (position, crop, divider) => {
              const value = `${((position - crop) / divider * 100)}%`;
              return value;
            }
          getLightColor: |
            number => {
              if (number <= 190) {
                  return '#d6dfff';
                }
              else if (number <= 227) {
                return '#e2e7ff';
              }
              else if (number <= 264) {
                return '#f4f2ff';
              }
              else if (number <= 302) {
                return '#fff3f0';
              }
              else if (number <= 340) {
                return '#ffe6cf';
              }
              else if (number <= 378) {
                return '#ffd3a5';
              }
              else if (number <= 416) {
                return '#ffb86f';
              }
              else if (number <= 454) {
                return '#ff8c19';
              }
              else {
                  return 'transparent';
              }
            }


##### NIGHT IMAGE #####


        card:
          type: picture-elements
          image: '/local/floorplan/nighttime.png?v=1'
          style: |
              ha-card {
                background: transparent;
                width: 100%;
              }
          elements:


##### CONDITIONAL DAY IMAGE #####


            - type: conditional
              conditions:
                - entity: sun.sun
                  state: above_horizon
              elements:
                - type: image
                  entity: sun.sun
                  image: '/local/floorplan/daytime.png?v=1'
                  style:
                    height: 100%
                    width: 100%
                    left: 50%
                    top: 50%
                    mix-blend-mode: lighten
                    opacity: "${ states['sensor.sunlight_opacity'].state }"
                  action: none
                  tap_action:
                    action: none
                  hold_action:
                    action: none

##### LIGHT OVERLAY IMAGES #####

            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.hallbyra
                - image: '/local/floorplan/lights/hallway-drawer.png'
                - background-color: "${ getLightColor(states['light.hallbyra'].attributes.color_temp) }"
                - opacity: "${ setOpacity('light.hallbyra') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.hall_ytterdorr_1
                - image: '/local/floorplan/lights/hallway-ceiling-door.png'
                - opacity: "${ setOpacity('light.hall_ytterdorr_1') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.hall_sovrum_1
                - image: '/local/floorplan/lights/hallway-ceiling-bedrooms.png'
                - background-color: "${ getLightColor(states['light.hall_sovrum_1'].attributes.color_temp) }"
                - opacity: "${ setOpacity('light.hall_sovrum_1') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: switch.danslampa
                - image: '/local/floorplan/lights/living-room-dance-light.png'
                - opacity: "${ setOpacity('switch.danslampa') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.vardagsrumsbord
                - image: '/local/floorplan/lights/living-room-table.png'
                - background-color: "${ getLightColor(states['light.vardagsrumsbord'].attributes.color_temp) }"
                - opacity: "${ setOpacity('light.vardagsrumsbord') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.fonsterlampa_mot_uterum
                - image: '/local/floorplan/lights/living-room-tv-light.png'
                - opacity: "${ setOpacity('light.fonsterlampa_mot_uterum') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.fonsterlampa_vardagsrum
                - image: '/local/floorplan/lights/living-room-window.png'
                - opacity: "${ setOpacity('light.fonsterlampa_vardagsrum') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.trappa
                - image: '/local/floorplan/lights/staircase.png'
                - background-color: "${ getLightColor(states['light.trappa'].attributes.color_temp) }"
                - opacity: "${ setOpacity('light.trappa') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.kokslampa
                - image: '/local/floorplan/lights/kitchen-table.png'
                - background-color: "${ getLightColor(states['light.kokslampa'].attributes.color_temp) }"
                - opacity: "${ setOpacity('light.kokslampa') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.diskbank
                - image: '/local/floorplan/lights/kitchen-sink.png'
                - opacity: "${ setOpacity('light.diskbank') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.taklampa_signes_rum
                - image: '/local/floorplan/lights/signe-ceiling.png'
                - opacity: "${ setOpacity('light.taklampa_signes_rum') }"
                - background-color: "${ getLightColor(states['light.taklampa_signes_rum'].attributes.color_temp) }"
            
##### LIGHT CONTROL ICONS #####            
            
            - type: custom:decluttering-card
              template: light-controls
              variables:
                - entity: light.hallbyra
                - left: 51%
                - top: 56%
                - type: state-icon
                - name: "${ states['light.hallbyra'].attributes.friendly_name }"
                - icon: mdi:lamp
            - type: custom:decluttering-card
              template: light-controls
              variables:
                - entity: switch.danslampa
                - left: 22%
                - top: 48%
                - type: state-icon
                - name: "${ states['switch.danslampa'].attributes.friendly_name }"
                - icon: mdi:floor-lamp-dual
            - type: custom:decluttering-card
              template: light-controls
              variables:
                - entity: light.vardagsrumsbord
                - left: 43.5%
                - top: 20%
                - type: state-icon
                - name: "${ states['light.vardagsrumsbord'].attributes.friendly_name }"
                - icon: mdi:ceiling-light
            - type: custom:decluttering-card
              template: light-controls
              variables:
                - entity: light.trappa
                - left: 55%
                - top: 88%
                - type: state-icon
                - name: "${ states['light.trappa'].attributes.friendly_name }"
                - icon: mdi:coach-lamp
            - type: custom:decluttering-card
              template: light-controls
              variables:
                - entity: light.hall_ytterdorr_1
                - left: 42.5%
                - top: 76%
                - type: state-icon
                - name: "${ states['light.hall_ytterdorr_1'].attributes.friendly_name }"
                - icon: mdi:ceiling-light
            - type: custom:decluttering-card
              template: light-controls
              variables:
                - entity: light.hall_sovrum_1
                - left: 64%
                - top: 60%
                - type: state-icon
                - name: "${ states['light.hall_sovrum_1'].attributes.friendly_name }"
                - icon: mdi:ceiling-light
            - type: custom:decluttering-card
              template: light-controls
              variables:
                - entity: light.kokslampa
                - left: 28.6%
                - top: 82.4%
                - type: state-icon
                - name: "${ states['light.kokslampa'].attributes.friendly_name }"
                - icon: mdi:ceiling-light
            - type: custom:decluttering-card
              template: light-controls
              variables:
                - entity: light.diskbank
                - left: 15%
                - top: 67%
                - type: state-icon
                - name: "${ states['light.diskbank'].attributes.friendly_name }"
                - icon: mdi:ceiling-light
            - type: custom:decluttering-card
              template: light-controls
              variables:
                - entity: light.fonsterlampa_mot_uterum
                - left: 22%
                - top: 10%
                - type: state-icon
                - name: "${ states['light.fonsterlampa_mot_uterum'].attributes.friendly_name }"
                - icon: mdi:lamp
            - type: custom:decluttering-card
              template: light-controls
              variables:
                - entity: light.fonsterlampa_vardagsrum
                - left: 2%
                - top: 33%
                - type: state-icon
                - name: "${ states['light.fonsterlampa_mot_uterum'].attributes.friendly_name }"
                - icon: mdi:ceiling-light
            - type: custom:decluttering-card
              template: light-controls
              variables:
                - entity: light.taklampa_signes_rum
                - left: 59.5%
                - top: 33%
                - type: state-icon
                - name: "${ states['light.taklampa_signes_rum'].attributes.friendly_name }"
                - icon: mdi:ceiling-light