title: Floorplan
decluttering_templates: !include ./floorplan/lights.yaml
views:
  - title: Floorplan
    path: floorplan
    visible:
      - user: 7fdffcaeaaf54b98b330878819fde53b
    panel: true
    icon: 'mdi:floor-plan'
    badges: []
    cards:
      - type: 'custom:config-template-card'
        entities:
          - light.hallbyra
          - light.hall_sovrum_1
          - light.hall_ytterdorr_1
          - light.trappa
          - light.vardagsrumsbord
          - light.fonsterlampa_mot_uterum
          - light.fonsterlampa_vardagsrum
          - switch.danslampa
          - light.kokslampa
          - light.diskbank
          - light.taklampa_signes_rum
          - sensor.sunlight_opacity
        variables:
          floorplan:
            leftCrop: 63
            topCrop: 36
            bottomCrop: 10
            width: 1793
            height: 955
          setOpacity: |
            entity => {
              if(states[entity].state === 'on') {
                if (typeof states[entity].attributes.brightness !== 'undefined') {
                  return states[entity].attributes.brightness / 255;
                }
                return 1;
              }
              return 0;
            }
          setPosition: |
            (position, crop, divider) => {
              const value = `${((position - crop) / divider * 100)}%`;
              return value;
            }
          getLightColor: |
            number => {
              if (number <= 190) {
                  return '#d6dfff';
                }
              else if (number <= 227) {
                return '#e2e7ff';
              }
              else if (number <= 264) {
                return '#f4f2ff';
              }
              else if (number <= 302) {
                return '#fff3f0';
              }
              else if (number <= 340) {
                return '#ffe6cf';
              }
              else if (number <= 378) {
                return '#ffd3a5';
              }
              else if (number <= 416) {
                return '#ffb86f';
              }
              else if (number <= 454) {
                return '#ff8c19';
              }
              else {
                  return 'transparent';
              }
            }
        card:
          type: picture-elements
          image: '/local/floorplan/nighttime.png?v=1'
          style: |
              ha-card {
                background: transparent;
                width: 100%;
              }
          elements:
            - type: conditional
              conditions:
                - entity: sun.sun
                  state: above_horizon
              elements:
                - type: image
                  entity: sun.sun
                  image: '/local/floorplan/daytime.png?v=1'
                  style:
                    height: 100%
                    width: 100%
                    left: 50%
                    top: 50%
                    mix-blend-mode: lighten
                    opacity: "${ states['sensor.sunlight_opacity'].state }"
                  action: none
                  tap_action:
                    action: none
                  hold_action:
                    action: none
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.hallbyra
                - image: '/local/floorplan/lights/hallway-drawer.png'
                - background-color: "${ getLightColor(states['light.hallbyra'].attributes.color_temp) }"
                - opacity: "${ setOpacity('light.hallbyra') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.hall_ytterdorr_1
                - image: '/local/floorplan/lights/hallway-ceiling-door.png'
                - opacity: "${ setOpacity('light.hall_ytterdorr_1') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.hall_sovrum_1
                - image: '/local/floorplan/lights/hallway-ceiling-bedrooms.png'
                - background-color: "${ getLightColor(states['light.hall_sovrum_1'].attributes.color_temp) }"
                - opacity: "${ setOpacity('light.hall_sovrum_1') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: switch.danslampa
                - image: '/local/floorplan/lights/living-room-dance-light.png'
                - opacity: "${ setOpacity('switch.danslampa') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.fonsterlampa_mot_uterum
                - image: '/local/floorplan/lights/living-room-tv-light.png'
                - opacity: "${ setOpacity('light.fonsterlampa_mot_uterum') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.fonsterlampa_vardagsrum
                - image: '/local/floorplan/lights/living-room-window.png'
                - opacity: "${ setOpacity('light.fonsterlampa_vardagsrum') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.trappa
                - image: '/local/floorplan/lights/staircase.png'
                - background-color: "${ getLightColor(states['light.trappa'].attributes.color_temp) }"
                - opacity: "${ setOpacity('light.trappa') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.kokslampa
                - image: '/local/floorplan/lights/kitchen-table.png'
                - background-color: "${ getLightColor(states['light.kokslampa'].attributes.color_temp) }"
                - opacity: "${ setOpacity('light.kokslampa') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.diskbank
                - image: '/local/floorplan/lights/kitchen-sink.png'
                - opacity: "${ setOpacity('light.diskbank') }"
            - type: custom:decluttering-card
              template: ikea-light
              variables:
                - entity: light.taklampa_signes_rum
                - image: '/local/floorplan/lights/signe-ceiling.png'
                - opacity: "${ setOpacity('light.taklampa_signes_rum') }"
                - background-color: "${ getLightColor(states['light.taklampa_signes_rum'].attributes.color_temp) }"
            - entity: light.hallbyra
              hold_action:
                action: call-service
                service: browser_mod.popup
                service_data:
                  title: "${ states['light.hallbyra'].attributes.friendly_name }"
                  deviceID: this
                  card:
                    type: entities
                    entities:
                      - type: custom:light-popup-card
                        entity: '${ states["light.hallbyra"].entity_id }'
                        icon: none
                        fullscreen: false
                        brightnessWidth: 130px
                        brightnessHeight: 360px
                        borderRadius: 1.7rem
                        sliderColor: '#c7c7c7'
                        sliderTrackColor: rgba(25, 25, 25, 0.9)
                        actionSize: 4.5em
                        actionsInARow: 2
                        style: |
                          #popup {
                            margin: -2.4em 0 1.4em 0; }
                          #popup > div.range-holder > input[type=range] {
                            cursor: grab; }
                          #brightnessValue {
                            color: rgba(255, 255, 255, 0.8); margin: -1.9em 0 0 0; font-size: 2em; font-weight: 400; 
                            position: absolute; z-index: 100; font-family: 'Roboto', sans-serif; letter-spacing: 0.02em; pointer-events: none; 
                            mix-blend-mode: difference; text-align:center; width: 3.4em; height: 3.4em; }
                          #popup > div.range-holder > input[type=range]::-webkit-slider-thumb {
                            border: 0; eight: 0; width: 0; cursor: grabbing; }
                          #popup > div.action-holder > div > div {
                            margin: 0.8em 0.5em -0.8em 0.5em; }
                          #popup > div.action-holder > div:last-child > div:last-child > .color {
                            background: radial-gradient(circle, rgba(255,255,255,1) 0%, rgba(255,255,255,0) 80%), 
                            conic-gradient(rgb(120,39,230), rgb(230,34,231), rgb(228,5,136), rgb(228,25,25), rgb(229,105,30), rgb(232,226,46), 
                            rgb(125,230,41), rgb(52,232,40), rgb(51,231,92), rgb(52,232,224),rgb(32,125,229), rgb(18,39,229), rgb(120,39,230));
                            border-width: 2px; border-color: #e6e6e6; --size: 4.4em !important; }
                        actions:
                          - service: light.turn_on
                            service_data:
                              entity_id: '${ states["light.hallbyra"].entity_id }'
                              color_temp: 153
                            color: "#d8d9e1"
                          - service: light.turn_on
                            service_data:
                              entity_id: '${ states["light.hallbyra"].entity_id }'
                              color_temp: 326
                            color: "#d5b08d"
                          - service: light.turn_on
                            service_data:
                              entity_id: '${ states["light.hallbyra"].entity_id }'
                              color_temp: 500
                            color: "#ce944b"
                          - service: browser_mod.popup
                            service_data:
                              title: '${ states["light.hallbyra"].attributes.friendly_name }'
                              deviceID: this
                              card:
                                type: entities
                                show_header_toggle: false
                                entities:
                                  - entity: '${ states["light.hallbyra"].entity_id }'
                                    secondary_info: last-changed
                                  - type: custom:light-entity-card
                                    entity: '${ states["light.hallbyra"].entity_id }'
                                    brightness: false
                                    color_temp: true
                                    white_value: true
                                    full_width_sliders: true
                                    hide_header: true
                                    show_slider_percent: true
                                    smooth_color_wheel: false
                                    consolidate_entities: true
              icon: 'mdi:lamp'
              style:
                '--iron-icon-height': 1.7vw
                '--iron-icon-width': 1.7vw
                '--paper-item-icon-active-color': '#000000'
                '--paper-item-icon-color': darkgrey
                align-items: center
                background-color: '#FFFFFF'
                border-radius: 100%
                box-shadow: '0px 0px 28px 0px rgba(0,0,0,0.39)'
                display: flex
                height: 2.4vw
                justify-content: center
                left: 50%
                margin-left: '-1.2vw'
                margin-top: '-1.2vw'
                top: 55%
                transform: scale(1.2)
                width: 2.4vw
              tap_action:
                action: toggle
              type: state-icon